### ISSUE TITLE
Modularisation of the whole project.

### ISSUE THREAD

**Issue by mrinal4** [garimasingh128/gitsetgo#1]
Put all JS Files and images in a directory and update the README as per the changes.

**Comment by Shruti3004** [comment]
@garimasingh128  @mrinal41298 I wanted to work on this issue could you give me a little more description about it.

**Comment by garimasingh128** [comment]
You just have to modularise it means create a separate folder for every type of file. For example: there are some images present in the components folder. Create a separate folder for them by name "images" and add every image of the project to it and make necessary changes to the code wherever those images are used. You just make the project pretty and decluttered as it is currently.

**Comment by Shruti3004** [comment]
okay
