### ISSUE TITLE
Location symbol change

### ISSUE THREAD

**Issue by garimasingh128** [garimasingh128/gitsetgo#103]
the location symbol would look much rather effective if it uses the default GitHub location/ the generic location icon

**Comment by rawdanowicz** [comment]
Hey,
looks pretty simple, I can do that!

**Comment by adityaraute** [comment]
One more open issue with a merged PR. I am trying to look for a `Beginner` issue to work on but many seem merged but not closed and also no comments on whether something is missing or not. I would strongly suggest closing Issues and PRs that are not active.
