### ISSUE TITLE
 Generate PDF not working

### ISSUE THREAD

**Issue by Gaushikmr** [garimasingh128/gitsetgo#14]
I tried to generate a pdf for my GitHub profile.but it's not working
From:https://gitsetgo.netlify.app/

**Comment by garimasingh128** [comment]
@gaushikmr it's working in my machine. See.
![Screenshot (558)](https://user-images.githubusercontent.com/44302373/89716720-02fed680-d9cd-11ea-931d-c43752825040.png)

**Comment by Gaushikmr** [comment]
@garimasingh128 In my device it's not working

**Comment by garimasingh128** [comment]
Try running it locally and checking the console!

**Comment by Gaushikmr** [comment]
@garimasingh128 ok

**Comment by Git-Harshit** [comment]
@gaushikmr It is working fine for me as well. Yes, it does take some little time (less than a minute) to get generated, please check for other factors as well, such as your internet speed, whether browser used is up-to-date, etc. 
If everything works fine, you can close the issue then.
