### ISSUE TITLE
Pull_request_template.md

### ISSUE THREAD

**Issue by ritiksoni00** [garimasingh128/gitsetgo#17]
**Is your feature request related to a problem? Please describe.*
there is no Pr_template.md file

**Describe the solution you'd like**
 I'd like to add a pr_template.md , so it is easy to understand what pr actually about!

**Comment by garimasingh128** [comment]
I believe it's already added. check here https://github.com/mrinal41298/gitsetgo/blob/master/pull_request_template.md

**Comment by ritiksoni00** [comment]
My bad...should it not be in the .github folder ???

**Comment by garimasingh128** [comment]
I don't think so. It's been working fine in my other projects!

**Comment by ritiksoni00** [comment]
i tried but it's not popping up  while making pr
![Annotation 2020-08-12 105647](https://user-images.githubusercontent.com/47344024/89978217-9ca6dc00-dc8a-11ea-9729-100bc0c12da8.png)

Or I'm doing some mistake??

**Comment by garimasingh128** [comment]
When you click on Create pull request button, then it pops up in the description field. Let me know if you find it!

**Comment by ritiksoni00** [comment]
got that! I think it must that pr.te.md file to be in .github folder! sorry for the disturbance
