### ISSUE TITLE
Related to Running it on Local System

### ISSUE THREAD

**Issue by yyash01** [garimasingh128/gitsetgo#18]
After successfully  cloning the project, Running (npm start) 
1. It returns the error due to npm modules, they were added by  developer side  only
2.after this Failed to compile due to -> (reason in the 
screenshot)
![Screenshot (95)](https://user-images.githubusercontent.com/54287899/90131454-cd216f80-dd89-11ea-933d-4ab50b620dad.png)

**Comment by AltCtrlDel1999** [comment]
Before running just perform "npm install" in gitsetgo repository that will resolve this error. It is not an issue @garimasingh128 close it.
