### ISSUE TITLE
When we enter a username that does not exist, the application does not display anything which is quite vague. 

### ISSUE THREAD

**Issue by garimasingh128** [garimasingh128/gitsetgo#19]
**Describe the bug**
When we enter a username that does not exist, the application does not display anything which is quite vague. What is to be done is as follows:
- Display a vector image of error or anything suitable as it is present on the landing page.
- Display the text "Username does not exist." below or beside the image.

You can use _conditional rendering_ of react to display the above things.

**Comment by AltCtrlDel1999** [comment]
I would like to work on this issue

**Comment by garimasingh128** [comment]
Go ahead. I hope you haven't been assigned to any other issue.

**Comment by nathzz30** [comment]
Hi, i want to ask you some question related to this PR, how can i test this bug? After that can i trying to resolve this? i want to Assign to me please.

**Comment by prem315** [comment]
This issue is still not fixed. I would like to contribute to this. We need to show the error message in the Alert component.

**Comment by prem315** [comment]
@garimasingh128 this issue has been fixed. 
some suggestions 
We should not write CSS using style={}
We could either write CSS in js using a third-party library like emotion-js or styled-components 
or we can write traditional CSS using .css or .scss file. for this approach, we can have a better folder structure like 

components/
  DispalyCard
     - displaycard.js
     - displaycard.css
  Footer
     - footer.js
     - footer.css

**Comment by garimasingh128** [comment]
Yes. We need to optimise all the css and stuff and organise it properly. I will open an issue for the same.
