### ISSUE TITLE
A splash screen can be added to improve the first user experience with the app.

### ISSUE THREAD

**Issue by mrinal4** [garimasingh128/gitsetgo#2]
A splash screen can be added to improve the first user experience with the app.
Create a design for the splash screen and add it to the project.

**Comment by Avirup-301294** [comment]
@garimasingh128 @mrinal41298 Can I take up this issue?

**Comment by garimasingh128** [comment]
Go ahead. Ping me up on slack for any design issues!

**Comment by Avirup-301294** [comment]
@garimasingh128 Please close this, it is completed.
