### ISSUE TITLE
Design of header changes

### ISSUE THREAD

**Issue by garimasingh128** [garimasingh128/gitsetgo#23]
As of now, the header looks quite simple and plain. Design and implement a new header with other important information. You can take inspiration from other websites and re-design it.

**Comment by yyash01** [comment]
I would like to Work on this issue.
Can you Tell Which header you are talking about is it of Website or The PDF's header which is generated ..?

**Comment by garimasingh128** [comment]
The header of the website with the GIF and the name. It looks okay as of now. Try finding some inspirations for style and color pallettes.

**Comment by Mitali-laroia** [comment]
I would like to work on this issue. I want to add animation to the header. As well as various text styling like giving it a light neon look, flickering or brick look.

**Comment by reyhhan** [comment]
Can I work on this?
