### ISSUE TITLE
The design in the mobile frame is not responsive in some places.

### ISSUE THREAD

**Issue by garimasingh128** [garimasingh128/gitsetgo#24]
The design in the mobile frame is not responsive in some areas. Also, when you click on Go ahead in mobile, it doesn't generates a resume and goes to the github repo due to click on the "fork me on github" ribbon. Make the website responsive and make changes to make it look good on all devices.

**Comment by Saicharan67** [comment]
I would like to work on it would u assign me?

**Comment by garimasingh128** [comment]
Sure go ahead

**Comment by Mitali-laroia** [comment]
I also want to work on this issue.

**Comment by avani-bit** [comment]
Hey I want to work on this issue

**Comment by Saicharan67** [comment]
Hey @garimasingh128  I have checked website in all mobile frames the problem is with "Form me on GitHub"  ribbon we should find an alternative for that because its covering some parts of header especially its covering the Title  "A Personalized GitHub Resume"

**Comment by garimasingh128** [comment]
Maybe try implementing something like this: https://tholman.com/github-corners/
Hopefully, it won't take that much space.

**Comment by Saicharan67** [comment]
Okay I will work on that

**Comment by garimasingh128** [comment]
@Saicharan67 please incorporate issue #66 also in the PR.
