### ISSUE TITLE
Adding pictures of Fork and Clone

### ISSUE THREAD

**Issue by sanchibansal340** [garimasingh128/gitsetgo#33]
**Is your feature request related to a problem? Please describe.**
As a beginner to GitHub,
1. People might not be able to find the fork and clone buttons. 
2. The Setup guidelines doesn't mention to fork the project which is necessary to create a pull request and thus can be confusing.

**Describe the solution you'd like**
1. I think it would be nice if pictures could be added to depict how to setup the project locally. Eg: Arrows pointing to Fork and Clone buttons
2. Adding a step to Fork the project in 'Steps to setup development environment' part of the README.

**Comment by garimasingh128** [comment]
Anyone who is assigned, please write detailed step form cloning to forking and finally creating a PR and asking for review in the README itself under the last heading steps to setup dev env.

**Comment by sanchibansal340** [comment]
Can I take this?

**Comment by sanchibansal340** [comment]
Made a pull request. Thanks @garimasingh128 :)

**Comment by sanchibansal340** [comment]
Hey @garimasingh128 @ShauryaBhandari . You can unassign me this issue. I have some other priorities right now and won't be able to contribute.

**Comment by garimasingh128** [comment]
@sanchibansal340 no issues!

**Comment by madhhuurrii** [comment]
Can i take this issue @garimasingh128

**Comment by madhhuurrii** [comment]
Hii ,I have created the pull request, i couldn't link the issue ,please review my PR @garimasingh128
