### ISSUE TITLE
Making the remaining links Clickable(Hyperlink) in the generated Resume(NOT PDF) and changing color of hyperlinks. 

### ISSUE THREAD

**Issue by kaushiksriram16** [garimasingh128/gitsetgo#34]
**Is your feature request related to a problem? Please describe.**
1. In the Generated Resume(NOT PDF) Blog and Github profile links are not hyperlink.
2. Hyperlinks are not differently colored.

**Describe the solution you'd like**
1. Adding anchor tags to the mentioned links
2. Changing the color of anchor tags in CSS

**Comment by kaushiksriram16** [comment]
I have sent a pull request of this one.

**Comment by tanishq98** [comment]
@ShauryaBhandari  @garimasingh128 I would like to work on this issue, as the link of github profile in generated resume (PDF) is not a hyperlink. It should be hyperlink so that a person can go from pdf version to the actual github profile directly by clicking on the hyperlink

**Comment by garimasingh128** [comment]
@kaushiksriram16  has already made a PR. Please look into that PR and mend if something is missing there.

**Comment by tanishq98** [comment]
@garimasingh128  have you merged that PR to the hakincodes branch?

**Comment by garimasingh128** [comment]
Not yet. Use this to check the code: https://gist.github.com/adam-p/15413fabef6cffecd897

**Comment by tanishq98** [comment]
@kaushiksriram16 has done perfect. But its done only on the web resume. 
@garimasingh128 I am doing this on PDF based resume. I am hyperlinking the links of blog and github profile in PDF version. So that the user can directly go to respective addresses directly.

**Comment by kaushiksriram16** [comment]
@tanishq98 then that's the issue #30

**Comment by tanishq98** [comment]
> @tanishq98 then that's the issue #30

Ohh Sorry, I didn't see that
