### ISSUE TITLE
The GitSetGo project needs to display a loader to ensure that a request is being made and is being processed

### ISSUE THREAD

**Issue by Git-Harshit** [garimasingh128/gitsetgo#37]
**Is your feature request related to a problem? Please describe.**
The Main Page is late to update, due to the request/response cycle. This delay goes unpredictable by the front user, who isn't aware about the entire process, making them frustrated at times when even a small, silly typo causes the request to return a NULL, which looks almost same as irresponsive app with a broken search link, which could have been better only if the loader screen were there to address every search query click with "Go Ahead".

**Describe the solution you'd like**
The app should display a loader icon or some other animation, so that the user can get ensured that there request is getting processed. This will also be useful to signal them to wait, instead of repeatedly pressing the "Go Ahead" button and generating more load on the server. 
Moreover, if in case no such GitHub profile handle was accessed and returned by GitHub API, then the main body can show some result message such as "Please Retry", "Profile not found.", "Failed to retrieve given GitHub Profile" or any other. 

**Describe alternatives you've considered**
Any working loader could be selected such as readymade free loaders (like at [Loading](https://loading.io/)).

**Additional context**
The profile page currently seems to be responding only when a successful request is made (i.e., the resume template changes only when some new results appear from GitHub API). 
![image](https://user-images.githubusercontent.com/57865187/90421125-8eb3e980-e0d6-11ea-9989-d71ba272ed27.png)

**Comment by garimasingh128** [comment]
Resources:
1. https://uxplanet.org/10-creative-loading-indicators-1a15c562b75a
2. loading.io

_For the part: Moreover, if in case no such GitHub profile handle was accessed and returned by GitHub API, then the main body can show some result message such as "Please Retry", "Profile not found.", "Failed to retrieve given GitHub Profile" or any other.
Additional context
The profile page currently seems to be responding only when a successful request is made (i.e., the resume template changes only when some new results appear from GitHub API)._

There's already an issue created for an unsuccessful request which says "user not found" with an image.

**Comment by Git-Harshit** [comment]
@garimasingh128 Thank you for looking into the issue, providing additional references, adding correct labels and for a quick response! 

> There's already an issue created for an unsuccessful request which says "user not found" with an image

My Bad, I should have noted that before this suggestion! 
Anyways, I believe implementing this while initiating a (maybe AJAX) request should do the needful! 😄

**Comment by divanshurox** [comment]
Hey can I work on this issue??
