### ISSUE TITLE
The current quality rating of the codebase is B. Make changes to the repo to make it reach A. 

### ISSUE THREAD

**Issue by mrinal4** [garimasingh128/gitsetgo#4]
Make changes to the repo to make it reach A.

**Comment by ritvij14** [comment]
@mrinal41298 how can we measure the quality rating? Also, how to know what improvements should be done to improve the rating?

**Comment by garimasingh128** [comment]
https://app.codacy.com/manual/garimasingh128/gitsetgo/issues/index  Here you go!

**Comment by ritvij14** [comment]
@garimasingh128 thanks for the link. Can I take up this issue and start working on it?

**Comment by garimasingh128** [comment]
Sure. But this is an ongoing issue as code will be changed many times. What you can do is to solve the existing issues currently.
