### ISSUE TITLE
Demo Template in the home page

### ISSUE THREAD

**Issue by ghost** [garimasingh128/gitsetgo#40]
**Is your feature request related to a problem? Please describe.**
The Page overall needs primary attention for a user or a developer while the first visit. UI enhancements in the landing Page.

**Describe the solution you'd like**
A minified landing page to attract users and have a demo portfolio without entering the username.

**Describe alternatives you've considered**
We can show it's working as a demo Gif.

**Comment by Avirup-301294** [comment]
@JoshuaPoddoku @garimasingh128 Can I take up this issue?

**Comment by garimasingh128** [comment]
There's already a similar issue that is assigned to someone else. You can look up for it and help the other assignee or claim some other issue.

**Comment by Avirup-301294** [comment]
Yes, the splash screen issue#2 which is similar with this assigned to me.

**Comment by garimasingh128** [comment]
Ya then implement the features of both in a single PR. we will close both issues then.

**Comment by Avirup-301294** [comment]
ok.

**Comment by Avirup-301294** [comment]
@garimasingh128 Please close this, it is completed.
