### ISSUE TITLE
Generated resume vanishes when we hit reload.

### ISSUE THREAD

**Issue by kaushiksriram16** [garimasingh128/gitsetgo#44]
**Describe the bug**
Generated resume vanishes when we hit reload and we have to enter username again to get it, instead it should stay.

**Expected behavior**
resume should stay even after the page refreshes.

**Comment by ritvij14** [comment]
@garimasingh128 I wanted to take this one, but I am new to this concept, so correct me if I am wrong.
For this, we can store the username entered in the `sessionStorage` right? I found on MDN docs that a session lasts as long as the browser is open and survives the reload of the website.

So will this issue be solved if we store the username in `sessionStorage` and just check at the start of the website if `sessionStorage` has anything? If it does we can call the function which fetches data and creates a component.
I would like to take this issue if this approach looks correct.

**Comment by garimasingh128** [comment]
I believe that your approach is correct. you may progress with it and ask doubts to any of the mentors.

**Comment by ritvij14** [comment]
We can close this now, right?
