### ISSUE TITLE
Add turven to the site.

### ISSUE THREAD

**Issue by garimasingh128** [garimasingh128/gitsetgo#47]
turven lets people on your website see how many other people are also reading the same page 👀

Link: https://github.com/maximevaillancourt/turven

**Comment by mharshita** [comment]
@garimasingh128  I want to work on this issue. Please assign this to me for HakinCodes 2020.

**Comment by mharshita** [comment]
@garimasingh128  Do I need to make a PR to add this website to turven's Readme as well ?

**Comment by garimasingh128** [comment]
No I'll do so. You can add a brief about it this repo's README. Just find a suitable place, add 1-2 lines and a link to Turven's repo.
