### ISSUE TITLE
Organisation not getting displayed

### ISSUE THREAD

**Issue by Yuvraj-kadale** [garimasingh128/gitsetgo#50]
**Describe the bug**
Users organizations are not getting displayed

**To Reproduce**
1. Go to 'gitsetgo.netlify.app'
2. Click on 'go-ahead'
3. Scroll down to 'Organisations'

**Expected behavior**
Expected to display the organization of user

**Screenshots**

My Organisations in GitHub profile
![Capture](https://user-images.githubusercontent.com/43489758/90808505-bfe22300-e33d-11ea-9aa5-0b92324afd1f.JPG)

Organization section is blank
![Capture](https://user-images.githubusercontent.com/43489758/90808626-f28c1b80-e33d-11ea-808c-f244f73e374f.JPG)

**Desktop (please complete the following information):**
 - OS: [e.g. windows]
 - Browser [e.g. firefox]
 - Version [e.g. 72]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by garimasingh128** [comment]
![Screenshot (570)](https://user-images.githubusercontent.com/44302373/90810141-236d5000-e340-11ea-95a0-d4a8db5091d1.png)
The organizations display those only which you are an admin of. If you want to display the member org also, create a feature request issue.

**Comment by Yuvraj-kadale** [comment]
> 
> 
> ![Screenshot (570)](https://user-images.githubusercontent.com/44302373/90810141-236d5000-e340-11ea-95a0-d4a8db5091d1.png)
> The organizations display those only which you are an admin of. If you want to display the member org also, create a feature request issue.

@garimasingh128 Alright! created a featured request of the same!!

**Comment by ritvij14** [comment]
@Yuvraj-kadale the issue that was created as a feature request for this has been closed and we can see organizations now. I think we can close this.

**Comment by Yuvraj-kadale** [comment]
> 
> 
> @Yuvraj-kadale the issue that was created as a feature request for this has been closed and we can see organizations now. I think we can close this.

@ritvij14 Yes bro great!!
