### ISSUE TITLE
Adding favicon

### ISSUE THREAD

**Issue by AshutoshDash1999** [garimasingh128/gitsetgo#52]
I want to add a favicon to the website, which will look good on website title bar. Can I submit a PR on this?

**Comment by garimasingh128** [comment]
The favicon is already present in public folder by the name favicon. I think it broke after merging a PR. Use that in index.html or if you have any other design options, suggest them here in the comments.

**Comment by AshutoshDash1999** [comment]
the favicon present is public folder is of react made by default. what about it?
![GSG](https://user-images.githubusercontent.com/46455250/90960096-e5496b00-e4bc-11ea-9b4a-c77a54927738.png)

Let me know if you want some different font. I took the background color from the site itself.

**Comment by garimasingh128** [comment]
Talking about this: https://github.com/garimasingh128/gitsetgo/blob/master/public/images/favicon.png

for the above suggestion, we can have a circular one with an octocat or something or something which speaks of resume. The above looks quite simple.

**Comment by AshutoshDash1999** [comment]
What about it? An octocat with a tie!
![Untitled design](https://user-images.githubusercontent.com/46455250/90961313-9a802100-e4c5-11ea-8975-044cdabe202a.png)

**Comment by garimasingh128** [comment]
I think you should just take inspiration from the octocat because if we use this, we may get copyright issues later. Maybe something different with a tie would look good.

**Comment by siddeshshewde** [comment]
How about this?
![octocat](https://user-images.githubusercontent.com/25485561/90967118-5a866180-e4f8-11ea-8867-a718f42aac5e.jpeg)

**Comment by garimasingh128** [comment]
I think it resembles the octocat so again copyright issues. Why don't you think of some other character or a simple decent favicon would also do just like how you suggested that violet one. Make it more aesthetic and round.

**Comment by AshutoshDash1999** [comment]
what about a simple suitcase? like this:
<img src="https://c7.uihere.com/files/890/625/263/briefcase-computer-icons-suitcase-baggage-simple-briefcase-icon-bag-baggage-breafcase-brief.jpg">
or this?
![circle-cropped](https://user-images.githubusercontent.com/46455250/90970812-0050c500-e527-11ea-8ad2-46420511f4a0.png)

**Comment by garimasingh128** [comment]
It is quite dark. Won't show up on title bar. @ShauryaBhandari Can you please guide him?

**Comment by AshutoshDash1999** [comment]
the suitacse one is just an example. I can turn it in white. What about the circular logo?
![circle-cropped](https://user-images.githubusercontent.com/46455250/90973063-1f0d8680-e53c-11ea-8e67-5fd6e2e336d2.png)

**Comment by garimasingh128** [comment]
Ya this looks good. Just centre the text and decrease the font size.

**Comment by AshutoshDash1999** [comment]
actually I was thinking instead of "GSG", it will be better if we use a single letter or icon because it will be appearing too small, so cluttering it with letters won't look good.
What about this?
![circle-cropped(1)](https://user-images.githubusercontent.com/46455250/90976663-6146c000-e55c-11ea-9d5f-3434b48b70f3.png)

**Comment by garimasingh128** [comment]
Looks good. But just reverse the colors, the purple won't show that much on black in title bar. Also, can you try other icons in same style like a bowtie or a tie on a white background

**Comment by AshutoshDash1999** [comment]
what about these?
1. ![GSG](https://user-images.githubusercontent.com/46455250/90979801-1b4a2600-e575-11ea-950a-b5733b55e041.png)
2. ![GSG(3)](https://user-images.githubusercontent.com/46455250/90979805-1d13e980-e575-11ea-80b5-dc5d4bdbf146.png)
3. <img height="50px" src="https://previews.123rf.com/images/sanek13744/sanek137441705/sanek13744170500152/77830318-tie-flat-icon-necktie-vector-illustration-.jpg">

**Comment by garimasingh128** [comment]
3 one looks good.
- remove the watermark
- make it round
- keep the bg white

**Comment by AshutoshDash1999** [comment]
is it fine?
![circle-cropped](https://user-images.githubusercontent.com/46455250/90983454-f7dea580-e58b-11ea-8b15-d7c3b7c658d3.png)

**Comment by garimasingh128** [comment]
Yup looks good

**Comment by AshutoshDash1999** [comment]
submitted a PR #55
