### ISSUE TITLE
Members organisation can  be added

### ISSUE THREAD

**Issue by Yuvraj-kadale** [garimasingh128/gitsetgo#53]
**Is your feature request related to a problem? Please describe.**
The users who are the admin of organizations are only displayed

**Describe the solution you'd like**
users as a member in the organisation can be added

**Describe alternatives you've considered**

**Additional context**

issue #50

**Comment by ritvij14** [comment]
To display the organizations of any user, we will need to refer to a different API endpoint. Currently, we use `data.company` for getting the company, but that's something that doesn't have the complete information. And it's not necessarily linked to the organization account either.

I think we should refer to a different endpoint for the organizations, to be specific `https://api.github.com/users/${username}/orgs` to get the organization data, that way we can put more and better info.

@garimasingh128 can we do this way? If yes, I would like to take this issue.

**Comment by garimasingh128** [comment]
Yeah you would need a different endpoint for it. Assigning you. Report within a week. Also, you can use cards, some highlights or just general bullets to displays the orgs. All the best!

**Comment by ritvij14** [comment]
@garimasingh128 This is what I have done. How does it look?
![image](https://user-images.githubusercontent.com/51456744/91874055-6233cc00-ec97-11ea-9f6b-1aa243ce73ee.png)

I also tried using anchor tags, but I don't know why they were all only in black color. I think there is some CSS property set for it which we might have to change, or maybe we can add some new class for this. Do we need an anchor tag to link names with the GitHub profiles of the organizations? We aren't getting links for those from the endpoint but we have login id from that so we can make it.

**Comment by garimasingh128** [comment]
I think instead of showing them in a column just show the logos in a row just like how Github shows and add the anchor tag to the image. For now, you can remove the org names and just show the logos. Also, you have to remove the default property in CSS of anchor tags to not show it in black.

**Comment by ritvij14** [comment]
@garimasingh128 ok.
I have made changes like this and the logos are placed in the anchor tags:
![image](https://user-images.githubusercontent.com/51456744/91881228-cad27700-ec9e-11ea-98d2-6955f2de149a.png)

**Comment by garimasingh128** [comment]
Ya it looks good!

**Comment by garimasingh128** [comment]
Maybe you can try with someone who has many organizations and see how it looks. It should not look too crowded!

**Comment by ritvij14** [comment]
@garimasingh128 yep it works fine
![image](https://user-images.githubusercontent.com/51456744/91885742-e8570f00-eca5-11ea-9e15-94d7ae7350f8.png)

I will make PR if it seems good?

**Comment by garimasingh128** [comment]
Looks good. Make a PR 👍🏽
