### ISSUE TITLE
Add shields, GIF's and badges to the readme.

### ISSUE THREAD

**Issue by garimasingh128** [garimasingh128/gitsetgo#54]
- Add necessary shields and badges at the right places in README. Link: https://shields.io
- Add fun GIF's and images in the readme. Inspiration: https://github.com/anushbhatia/Social-Scheduler

**Comment by Avirup-301294** [comment]
@garimasingh128 Can i take up this issue?

**Comment by ShauryaBhandari** [comment]
@Avirup-301294  Are you still working on this issue? 
If yes, no issues
If not, please let me know, I will assign it to someone else

**Comment by Avirup-301294** [comment]
I already completed and make pr of all the 3 task i have assigned in 1 pr which is already merged.

**Comment by ShauryaBhandari** [comment]
Ah, it was merged in the common PR. 
Apologies, I lost track of it!

**Comment by garimasingh128** [comment]
@Avirup-301294 please mention the issues in the pr description otherwise the solved issues remain open!
