### ISSUE TITLE
Add tech stack badges to resume

### ISSUE THREAD

**Issue by ShauryaBhandari** [garimasingh128/gitsetgo#61]
Badges/SVGs can be used to highlight the tech stack of the person. 

As I feel it always helps a recruiter get a better insight into the person, as all of them just glance through over the resumes and not actually read it line by line. 

We could add the languages/tech stack used by the person to the document in a better and visual way so it also makes the document look aesthetic. 
**EDIT 1:**
Add the top 3 languages the person has dealt the most in, in the violet panel.

Open to discussion.

**Comment by ShauryaBhandari** [comment]
@garimasingh128 sounds good?

**Comment by garimasingh128** [comment]
Ya great idea. They can be kept in the violet panel or below the name. Also, the badges should be of the top 3 tech stacks or languages the person has the most repos in. In that way it would be easier. @ShauryaBhandari please assign the issue labels here.

**Comment by ritvij14** [comment]
I am curious as to how we can find this? I know about Github README stats, but is there some tool to get the top languages/tech stack that person has used based on their github repository data?

**Comment by garimasingh128** [comment]
I think you can do this by creating a hashmap for the languages and the number of times they have been used in all repos. The data for the languages used comes with the response from repository data. Then display the top 3. For the badges, you can use simple if else for all major languages probably 10-12 i.e. if top language is for ex python, then display the badge for pyhton which you can get from shields.io.

**Comment by garimasingh128** [comment]
I don't know how README stats work so if you find easier to understand them, then try that.

**Comment by ShauryaBhandari** [comment]
There are various ways/ third party ways to retrieve the data. 
Only for that reason, I have added a medium level badge! You can use any way you are comfortable with.

**Comment by ritvij14** [comment]
Ok I will do some research and then start implementing it. Please assign this to me.
