### ISSUE TITLE
Site Responsive Improvements

### ISSUE THREAD

**Issue by Avirup-301294** [garimasingh128/gitsetgo#66]
Site should be responsive in all layout. When we change the screen size, the content in the jsx element changes and it is not in proper ordered.  When we change the screen size, the generate pdf button overlapped with the profile section.

Additionally, a changing theme button or a toggler may be a better layout for different themes. we can also add a toggler for fonts which are frequently used in resumes.

**Comment by garimasingh128** [comment]
There was already an issue created for responsiveness I think or probably is. Please check that out!

**Comment by Avirup-301294** [comment]
Yes, you are right, you raised that issue but that was related to only mobile frames. 
I found the responsive issue in all places. In Desktop when we increase the screen size it overlaps with the profile section. I found the place of the text "the personalized github profile" in the header is also shifting

**Comment by garimasingh128** [comment]
Maybe we can solve both in a single PR. I am assigning tags as of now but the assignee has to solve both of these issues! :)

**Comment by Avirup-301294** [comment]
Shall I delete this and if you want to add something from this then you can edit the issue you raised. It will be better for the assignee. Otherwise it is not necessary.

**Comment by garimasingh128** [comment]
Okay I will add there. CLose this one!
