### ISSUE TITLE
Add more info about user if they have created a README for their profile.

### ISSUE THREAD

**Issue by ritvij14** [garimasingh128/gitsetgo#74]
**Is your feature request related to a problem? Please describe.**
The about section sometimes doesn't show much about the person. And with the new GitHub feature of creating a repository with their own username, more and more people have started creating their very own GitHub README repositories.

**Describe the solution you'd like**
Would it be a good idea to add the info from a user's GitHub README repo (if he/she has made one)? I think we might be able to put in a good amount of info with the help of this feature.

**Comment by ritvij14** [comment]
@garimasingh128 does this sound like a good feature to add? If yes I would like to do this.

**Comment by garimasingh128** [comment]
The idea is good but I have an issue that the README of the special repo does not have a word limit and if we show it completely, a whole page would be wasted in about section. So, should we have a word limit, and if yes, where should the limit end?

**Comment by ritvij14** [comment]
Yes, you are right, I didn't think about it. 
Now that I remember seeing other README from various profiles, I think not only the world limit but also stuff which should not be put on a Resume (stickers, memes, gifs) would also make a problem. I think this might be a feature for which we would need a clever way to filter out exactly what content to be shown, but that basis of filtering might not be the same for everyone.
