### ISSUE TITLE
Readme updation for participants according to Hackincodes program.

### ISSUE THREAD

**Issue by garimasingh128** [garimasingh128/gitsetgo#75]
- You can write separate guidelines for general participants and for hackincodes participants to create PRs on develop and hackincodes branch respectively

- You should also write a small description of how to create a PR. Like the steps to add and commit and then going to the browser to create a PR and change the base branch if needed.

- Add memes and GIFs' to the readme to make it interesting.

**Comment by AdityaAshvin** [comment]
Can I do this? @garimasingh128
