### ISSUE TITLE
Style the tables displaying repos

### ISSUE THREAD

**Issue by ShauryaBhandari** [garimasingh128/gitsetgo#76]
The functionality has been added, someone with a good design quotient can style the tables in a better manner.

**Comment by tanishq98** [comment]
I want to work on this

**Comment by ritvij14** [comment]
@ShauryaBhandari how does this look?
![image](https://user-images.githubusercontent.com/51456744/93555200-f047cc00-f992-11ea-92d4-0d55fa58f2fb.png)

If this looks good I can make a quick PR for this issue as I have already done the changes. If you have more ideas, please suggest as I am still pretty new o designing stuff :sweat_smile: 

One problem with the part of the `languages` is that we cannot show the languages for the forked repos. What should we do about that? I feel keeping them empty is a bit weird.

**Comment by ritvij14** [comment]
@garimasingh128 I have completed my previous task, so can I take this one?

I have added a mock of how the table looks like in the previous comment.

> One problem with the part of the languages is that we cannot show the languages for the forked repos. What should we do about that? I feel keeping them empty is a bit weird.

What should we do about this?

**Comment by garimasingh128** [comment]
for the forked repos, see if you can filter out them and include only personal repos as they are those projects to which he/she has contributed and not his/her personal projects. So remove them for now.

**Comment by ritvij14** [comment]
@garimasingh128 I filtered the forked ones out, this is how it looks.
![image](https://user-images.githubusercontent.com/51456744/93729307-91c45d00-fbe1-11ea-800d-9e25a075e62f.png)

There is also an API endpoint in the `repos` endpoint. The `languages_url` shows languages for forked repositories even if `language` data is null. But we will have to fetch them.

**Comment by garimasingh128** [comment]
I think this looks fine. Forked repos have no meaning showing them in a resume as the user might not even contributed to them. Looks good. Make a OR for this.

**Comment by ritvij14** [comment]
Alright, will do asap. Please assign this to me.
