### ISSUE TITLE
Remove empty fields

### ISSUE THREAD

**Issue by ShauryaBhandari** [garimasingh128/gitsetgo#77]
If any information is not obtained from the GitHub handle, remove the placeholder for that as well. 
For example, many people are not on twitter, so for them that should be removed from the generated UI.

**Comment by ritvij14** [comment]
I would like to work on this issue.

**Comment by garimasingh128** [comment]
@ShauryaBhandari Is this same or similar as https://github.com/garimasingh128/gitsetgo/issues/13?

**Comment by ShauryaBhandari** [comment]
Yes it is, my bad. That was an old issue I did not go through. Should I close this one?

**Comment by garimasingh128** [comment]
Yeah!

**Comment by ShauryaBhandari** [comment]
Closed as issue already exists.
