### ISSUE TITLE
Changing PDF file name for the resume

### ISSUE THREAD

**Issue by garimasingh128** [garimasingh128/gitsetgo#83]
As of now, the generated PDF file has the name "github_resume" which sounds vague and odd. Change the file name to "Username_Github_Resume". 
```
For ex: Garima Singh_Github_Resume.
```

**Comment by kritikaparmar-programmer** [comment]
Hey @garimasingh128 I want to work on this issue.. Please assign me..

**Comment by kritikaparmar-programmer** [comment]
Hey @garimasingh128  pls take a look at this change 
![pdffff](https://user-images.githubusercontent.com/59971890/93460581-0c029200-f901-11ea-9a5f-efccaf6681b4.png)

Did this will solve the problem.. As I'm new to JS that's why I'm asking.. hope you would not mind 😅

**Comment by garimasingh128** [comment]
I am not sure if it would work. Why don't you include the username parameter in newlocal and change its type? Or you can try generating the PDF and see if your method works.

**Comment by kritikaparmar-programmer** [comment]
Hey @garimasingh128 I run the project and the pdf name that was generated was username of the person..
Can you suggest something?? Or let it be username only..

**Comment by garimasingh128** [comment]
Format: Garima Singh_Github_Resume
