### ISSUE TITLE
Fix the margins between buttons on mobile view. 

### ISSUE THREAD

**Issue by ShauryaBhandari** [garimasingh128/gitsetgo#88]
The header looks really cluttered on smaller screen sizes. 
Fix the margins between buttons and other elements.

**Comment by nikita-1801** [comment]
I'd like to work on this.

**Comment by ShauryaBhandari** [comment]
Assigned to @nikita-1801!

**Comment by Mu-C00L** [comment]
I want to work on this issue

**Comment by nikita-1801** [comment]
I've completed working on this issue and am just about to make a PR
