### ISSUE TITLE
Unnecessary white space. 

### ISSUE THREAD

**Issue by ShauryaBhandari** [garimasingh128/gitsetgo#89]
There is a lot of unneeded white space above the profile picture in the resume, when viewed on mobile mode, needs minor fixing.

**Comment by ritvij14** [comment]
I would like to work on this.

**Comment by ShauryaBhandari** [comment]
Assigned to @ritvij14

**Comment by reyhhan** [comment]
I would like to pull this up for Hacktoberfest

**Comment by ShauryaBhandari** [comment]
@garimasingh128 Please look into this.

**Comment by nathzz30** [comment]
I would like to work on this, can you Assign to me too? Thank you

**Comment by melissahuertadev** [comment]
Hi, if this is still open, I would like to work on this for #Hacktoberfest 😊
