### ISSUE TITLE
Need to add dark and light theme!

### ISSUE THREAD

**Issue by mrinal4** [garimasingh128/gitsetgo#9]

**Comment by sanchibansal340** [comment]
Can I work on this?

**Comment by AdityaAshvin** [comment]
can i work on this issue? @ShauryaBhandari @mrinal41298  ?

**Comment by ShauryaBhandari** [comment]
Yes, @AdityaAshvin. Assigned to you. 
@sanchibansal340, It has been over 10 days, so we are assigning it to someone else.

**Comment by sanchibansal340** [comment]
I tried a solve it but wasn't able to. I was about to inform. Thank you for giving me the time

**Comment by ShauryaBhandari** [comment]
No problem @sanchibansal340 ! Pick up some other issue which is easier and quicker to solve. Please let me know if you encounter any problems

**Comment by AdityaAshvin** [comment]
![light_theme](https://user-images.githubusercontent.com/53205379/91531456-72ac1580-e92a-11ea-8479-4b1a3778ab80.JPG)
This is the light theme which can be used. @garimasingh128 and @ShauryaBhandari  your views on this? Any changes to be made?

**Comment by garimasingh128** [comment]
We can have the search bar also in dark grey with white text.
Adda switch in the navbar for changing themes. The switch can be a bit creative.

The rest looks good I think.

**Comment by AdityaAshvin** [comment]
okay. These changes will be implemented.
